# Generated by Django 4.2.30 on 2026-05-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reason',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='Другое', max_length=50),
        ),
    ]
