# Generated by Django 4.2.30 on 2026-05-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_transaction_reason_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
